export interface Florist {
    id?: number;
    floristname?: string;
    contactnumber?: string;
    address?: string;
    city?: string;
    province?: string;
    postcode?: string;
    website?: string;
    socialmedia?: string;
    collection?: string;
    status?: string;
    shopifygid?: string;
    call_outcome?: string;
    product_type?: string;
    product_price?: string;
    delivery_fee?: string;
    sell_extras?: string;
    popularity_trend?: string;
    preferred_communication?: string;
    member_of_other_networks?: string;
    flower_supplier?: string;
    interested_free_website?: string;
    discout_offer?: string;
    additional_info?: string;
    page_title?: string;
    meta_description?: string;
    description?: string;
    city_name?: string | null;
    province_name?: string | null;
    floristrep_name?: string | null;
    status_name?: string | null;
    floristrep?: string | null;
    photo_url?: File | null;
};
